module(name = "osal", version = "0.0.1")

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "googletest", version = "1.17.0", repo_name = "com_google_googletest")

single_version_override(
    module_name = "googletest",
    version = "1.17.0",
    patches = [
        "//patches:googletest_build.patch",
        "//patches:googletest_module.patch",
    ],
    patch_strip = 1,
)
# Bzlmod HTTP Archive rules for FreeRTOS Kernel
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "freertos",
    urls = ["https://github.com/FreeRTOS/FreeRTOS-Kernel/archive/refs/tags/V10.4.3.tar.gz"],
    integrity = "sha256-bihGYHf/Qt4dXctnnIzs9GNw/Z6OhuueJ67vhePN1Pk=",
    strip_prefix = "FreeRTOS-Kernel-10.4.3",
    build_file_content = """
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "freertos_kernel",
    hdrs = glob([
        "include/*.h",
        "portable/ThirdParty/GCC/Posix/*.h",
    ]),
    includes = [
        "include",
        "portable/ThirdParty/GCC/Posix",
    ],
    visibility = ["//visibility:public"],
)
"""
)
